apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-todo
  template:
    metadata:
      labels:
        app: django-todo
    spec:
      containers:
      - name: todoapp-container
        image: chandrasaid/todo-monitoring:latest
        ports:
        - containerPort: 8000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret  # The name of your Kubernetes secret
              key: AWS_ACCESS_KEY_ID  # The key within the secret
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_STORAGE_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_STORAGE_BUCKET_NAME
        - name: AWS_S3_REGION_NAME
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_S3_REGION_NAME
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
