apiVersion: v1
kind: Service
metadata:
  name: django-todo
  labels:
    app: django-todo
spec:
  type: NodePort
  ports:                          
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
  selector:
    app: django-todo
